### ISSUE TITLE
Suggestion: Renaming LIGHT to ANALOG IN

### ISSUE THREAD

**Issue by kotobuki** [kotobuki/M5Stack-HID-Input-Framework-for-xR#2]
Since LIGHT is just an analogue sensor, users can use other analogue sensors such as ANGLE. Therefore, how about renaming `LIGHT` to `ANALOG IN` to let users know that the setting is versatile?

**Comment by tim003** [comment]
I think it is a good idea. In this case, the "how to setup" session might need to add one note "to use Analog in of light sensor" to make it clear for users reading the instruction by themselves
